# Data Analysis using python
## Data Analysis 
### Data Analysis
#### Data Analysis
##### Data Analysis
###### Data Analysis

### Python
- List
    - []
- Tuple
    - ()
- Strings
    - " " or ' '
- Dict
    - {}
- Sets
    - {}
- Files
- Functions
- Oops

- *welcome to apssdc*
- **welcome to apssdc**
- ***welcome to apssdc***

## Python Libraries
- Numpy

In [1]:
# create 1D array
import numpy
a = numpy.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
# create 2D array
import numpy as np
a1 = np.array([[1,2,3],[4,5,6]])
print(a1)

[[1 2 3]
 [4 5 6]]


In [3]:
# create 3D array
import numpy as np
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
a1.ndim

2

In [10]:
a2.size

9

In [14]:
a1.shape

(2, 3)

In [15]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a2[0]

array([1, 2, 3])

In [17]:
a2[1]

array([4, 5, 6])

In [18]:
a2[2]

array([7, 8, 9])

In [19]:
a2[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [20]:
a2[0:1,0:1]

array([[1]])

In [22]:
a2[1:,2:]

array([[6],
       [9]])

In [25]:
a2[1:,2:3]

array([[6],
       [9]])

In [30]:
np.random.random()

0.5887099665571962

In [31]:
np.random.randn(1)

array([1.69406001])

In [29]:
np.random.randn(1,10)

array([[ 0.5684106 , -3.85219722,  0.04333967,  0.41587662,  0.04628033,
        -0.8418676 ,  0.51611311, -1.2100408 ,  1.14068899,  0.23812902]])

In [35]:
a=np.random.randint(1,20,15)
print(a)

[ 9 16  3  9 13 13 17 17 18  4 10 10 11 13 11]
